sudo: false
language: perl

perl:
 - "5.10"
 - "5.12"
 - "5.14"
 - "5.16"
 - "5.18"
 - "5.20"

install:
 - cpanm --notest Dist::Zilla Dist::Zilla::PluginBundle::Author::ALEXBIO
 - dzil listdeps --missing | cpanm --notest

script:
 - dzil test

notifications:
  recipient:
   - alessandro@ghedini.me
  email:
    on_success: change
    on_failure: always
